# CentOS8
FROM centos:8
ENV CENTOS_ENV=DEV
 #Install vim editor
RUN yum -y install wget
RUN yum -y install vim
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]

# Apache Tomcat 9.0.63 + OpenJDK Version 11
#RUN --mount=type=bind,target=/app/container/ttbicollapp
RUN mkdir /app
RUN mkdir /app/motif
RUN mkdir /app/setup
RUN mkdir /app/setup/repository

#Set the WORKDIR path for work visits, and log in the foothold
ENV HOMEPATH /app
WORKDIR $HOMEPATH
#Configure java and tomcat environment variables
ENV JAVA_HOME /app/motif/ilegal/java/jdk1.8.0_171
ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV CATALINA_HOME /app/motif/ilegal/apache/apache-tomcat-8.5.51
ENV CATALINA_BASE /app/motif/ilegal/apache/apache-tomcat-8.5.51
ENV PATH $PATH:$JAVA_HOME/bin:$CATALINA_HOME/lib:$CATALINA_HOME/bin
#Specify Location
ENV TZ=Asia/Bangkok
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 #The port that the container is listening on
EXPOSE  8443