#!/bin/sh
### BEGIN INIT INFO
# Reference: http://stackoverflow.com/questions/6880902/start-jboss-7-as-a-service-on-linux
# Provides:          jboss
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop JBoss AS v7.1.1
### END INIT INFO
#
#source some script files in order to set and export environmental variables
#as well as add the appropriate executables to $PATH
#[ -r /etc/profile.d/java.sh ] && . /etc/profile.d/java.sh
#[ -r /etc/profile.d/jboss.sh ] && . /etc/profile.d/jboss.sh

#export JBOSS_HOME=/app/jboss/jboss-as-7.1.1.Final

case "$1" in
    start)
         echo "Starting JBoss AS 7.1.1"
        /bin/su - motif  /app/jboss/jboss-as-7.1.1.Final/bin/standalone.sh > /dev/null 2>&1&
    ;;
    stop)
        echo "Stopping JBoss AS 7.1.1"
        /bin/sh /app/jboss/jboss-as-7.1.1.Final/bin/jboss-cli.sh --connect command=:shutdown
    ;;
    *)
        echo "Usage: /etc/init.d/jboss {start|stop}"
        exit 1
    ;;
esac

exit 0
